name: smart
description: A new Flutter project.
publish_to: "none"
version: 1.0.43+49
# version: 1.0.42+49
#flutter version 3.7.9;

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.3.3
  flutter_svg: ^1.0.3
  mask_text_input_formatter: ^2.0.0
  pin_code_fields: ^7.2.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  fluttertoast: ^8.2.1
  flutter_toggle_tab: ^1.1.2
  yandex_mapkit: ^3.2.0
  flutter_slidable: ^0.6.0
  qr_flutter: ^4.0.0
  easy_mask: ^2.0.1
  pagination_view: ^2.0.0
  shimmer: ^2.0.0
  google_fonts: ^4.0.3
  flutter_keyboard_visibility: ^5.0.2
  email_validator: ^2.0.1
  firebase_messaging: ^14.3.0
  firebase_analytics: ^10.8.0
  flutter_local_notifications: ^8.0.0
  firebase_core: ^2.8.0
  url_launcher: ^6.1.7
  change_app_package_name: ^1.1.0
  easy_localization: ^3.0.0
  webview_flutter: ^2.1.1
  barcode_scan2: ^4.2.1
  flutter_displaymode: ^0.5.0
  # flutter_inappwebview: ^5.3.2
  location: ^5.0.3
  flutter_advanced_networkimage_2: ^2.0.1
  mime:
  rxdart: ^0.27.3
  story_view: ^0.14.0
  contacts_service: ^0.6.3
  package_info_plus: ^3.0.2
  latlong2: ^0.8.1
  top_snackbar_flutter: ^2.1.1
  lottie: ^2.3.2
  video_player:
  expandable_page_view:
  scrollable_positioned_list:
  auto_size_text_field: ^2.1.0
  animated_text_kit:
  # geolocator: ^9.0.2
  # anchor_scroll_controller: ^0.4.3
  flutter_native_splash: ^2.2.19
  collection: ^1.15.0
  carousel_slider_plus: ^7.0.1
  custom_will_pop_scope: ^2.1.1
  # upgrader: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/svgForSwitches/
    - assets/json/

  fonts:
    - family: KabelCTT Medium
      fonts:
        - asset: assets/fonts/KabelCTT-Medium.ttf
          weight: 400
        - asset: assets/fonts/KabelCTT-MediumBold.ttf
          weight: 700

flutter_intl:
  enabled: true
